"""Joint sup-LR test for a prespecified number of factor-model breaks.

This module implements the statistics and limiting distributions described by
Theorem 5 of the multiple-change extension of the factor-model LR test.
The supremum over admissible partitions is solved by dynamic programming.
"""

from typing import Dict, Optional

import numpy as np

import fmbqml.utils as U
from fmbqml.multiple_break.find_min_qml import find_min_qml
from fmbqml.statistical_tools import (
    factor_long_run_covariance,
    joint_sup_lr_cv,
    select_critical_value,
)

def _normalize_factors(F_hat: np.ndarray) -> np.ndarray:
    """Impose the full-sample PC normalization ``F'F/T = I``.

    Raises
    ------
    ValueError
        If the full-sample factor second-moment matrix is rank deficient.
    """
    gram = F_hat.T @ F_hat / len(F_hat)
    eigenvalues, eigenvectors = np.linalg.eigh(0.5 * (gram + gram.T))
    tolerance = np.finfo(float).eps * max(gram.shape) * max(1.0, np.max(eigenvalues))
    if np.min(eigenvalues) <= tolerance:
        raise ValueError("Estimated factors are rank deficient under full-sample normalization.")
    inverse_sqrt = (
        eigenvectors
        @ np.diag(1.0 / np.sqrt(eigenvalues))
        @ eigenvectors.T
    )
    return F_hat @ inverse_sqrt


def _run_joint_sup_lr(
    F_hat: np.ndarray,
    n_breaks: int,
    trim_ratio: float = 0.15,
    alpha: float = 0.01,
    n_sim: int = 5000,
    grid_size: int = 500,
    random_state: Optional[int] = None,
) -> Dict[str, object]:
    """Run the joint sup-LR test for a prespecified number of breaks.

    ``grid_size`` controls only the numerical approximation of the continuous
    Brownian-bridge supremum. The observed statistic is optimized on the full
    sample grid.

    Parameters
    ----------
    F_hat : ndarray of shape (T, r)
        Full-sample estimated factors.
    n_breaks : int
        Exact number of breaks under the alternative hypothesis.
    trim_ratio : float, default=0.15
        Minimum regime length as a fraction of the sample.
    alpha : {0.10, 0.05, 0.01}, default=0.01
        Significance level.
    n_sim : int, default=5000
        Number of Monte Carlo replications used for critical values.
    grid_size : int, default=500
        Brownian-bridge grid size used only in critical-value simulation.
    random_state : int or None, default=None
        Seed for reproducible critical-value simulation.

    Returns
    -------
    dict
        Test statistic, estimated breakpoints, critical values, rejection
        decision, objective values, and simulated limiting statistics.

    Notes
    -----
    Critical values are generated by :func:`joint_sup_lr_cv`, not by the
    single-break helper :func:`critical_value_lr_hac_m`.  The joint simulator
    optimizes over ``n_breaks + 1`` regimes simultaneously.
    """
    (
        F_hat,
        min_length,
        n_breaks,
        trim_ratio,
        alpha,
        n_sim,
        grid_size,
    ) = U.validate_joint_sup_lr_arguments(
        F_hat, n_breaks, trim_ratio, alpha, n_sim, grid_size
    )
    F_hat = _normalize_factors(F_hat)
    T = len(F_hat)

    alternative, breakpoint_array = find_min_qml(
        F_hat, T, min_length, n_breaks
    )
    breakpoints = [int(point) for point in breakpoint_array]
    null_value = T * U.safe_logdet(F_hat.T @ F_hat / T)
    statistic = max(0.0, null_value - alternative)

    omega = factor_long_run_covariance(F_hat, project_psd=True)
    critical_values, simulated = joint_sup_lr_cv(
        omega,
        n_breaks,
        trim_ratio,
        n_sim,
        grid_size,
        random_state,
    )
    critical_value = select_critical_value(critical_values, alpha)

    return {
        "test_type": "joint_sup_lr",
        "n_breaks": n_breaks,
        "breakpoints": breakpoints,
        "test_statistic": statistic,
        "critical_value": critical_value,
        "critical_values": {
            0.10: float(critical_values[0]),
            0.05: float(critical_values[1]),
            0.01: float(critical_values[2]),
        },
        "reject_null": bool(statistic > critical_value),
        "significance_level": float(alpha),
        "trim_ratio": float(trim_ratio),
        "min_segment_length": min_length,
        "grid_size": grid_size,
        "monte_carlo_replications": n_sim,
        "random_state": random_state,
        "null_objective": null_value,
        "alternative_objective": alternative,
        "simulated_statistics": simulated,
    }


__all__ = []
